create database students_marks;
use students_marks;
create table marksheet(rollno int,name text ,tamil int,english int,maths int, science int, social int,total int);
select * from marksheet;
insert into marksheet(rollno,name,tamil,english,maths,science,social,total)values(1,"karan",75,68,57,98,53,412);
insert into marksheet(rollno,name,tamil,english,maths,science,social,total)values(2,"karthi",45,75,25,85,41,358);
insert into marksheet(rollno,name,tamil,english,maths,science,social,total)values(3,"ran",74,71,85,77,33,687);
insert into marksheet(rollno,name,tamil,english,maths,science,social,total)values(4,"raj",78,68,57,71,41,382);
insert into marksheet(rollno,name,tamil,english,maths,science,social,total)values(5,"kamar",75,71,47,92,74,431);
insert into marksheet(rollno,name,tamil,english,maths,science,social,total)values(6,"kathir",75,65,55,41,61,354);
insert into marksheet(rollno,name,tamil,english,maths,science,social,total)values(7,"arun",45,56,58,88,43,358);
insert into marksheet(rollno,name,tamil,english,maths,science,social,total)values(8,"muthu",41,33,35,45,50,251);
insert into marksheet(rollno,name,tamil,english,maths,science,social,total)values(9,"kumaran",66,86,75,82,43,302);
insert into marksheet(rollno,name,tamil,english,maths,science,social,total)values(10,"sakthi",77,66,55,94,53,362);

select * from marksheet where tamil<=50;
select * from marksheet where total<=300;
select * from marksheet where tamil<=40 OR english<=40 OR maths<=40 OR science<=40 OR social<=40 ; 
select * from marksheet where tamil>=90 OR english>=90 OR maths>=90 OR science>=90 OR social>=90 ; 
select * from marksheet where tamil<=english;
select * from marksheet where name like 'k%'AND tamil>=50 AND english>=50 AND maths>=50 AND science>=50 AND social>=50; 
select * from marksheet order by name desc;
select * from marksheet limit 3;
select * from marksheet order by name desc limit 3;
select min(tamil) from marksheet;
select max(tamil) from marksheet;
select count(tamil) from marksheet;
select avg(tamil) from marksheet;
select sum(tamil) from marksheet;
select name from marksheet where science>=50 AND social>50;
select name from marksheet where  maths<=40 order by name desc;